### ISSUE TITLE
pupil coordinate changing

### ISSUE THREAD

**Issue by codeYazar** [antoinelame/GazeTracking#10]
Pupil markers flicker too. How to fix it
thanks

**Comment by antoinelame** [comment]
Hi,
Can you be more specific on your issue?
If on some frames, eyes markers (`gaze.annotated_frame()`) are missing, it means the algorithm didn't detect your face.

**Comment by codeYazar** [comment]
there is no problem in detecting the pupil. Although my eyes are fixed, the pupil marker coordinate is constantly changing 2-3 pixels.

**Comment by antoinelame** [comment]
Hi @codeYazar 
Unfortunately, I can't provide yet a level of accuracy that doesn't move by 2 or 3 pixels.
But if your goal is to move a mouse and you are annoyed by that, you can code a small algorithm that smoothes the coordinates movements. It's up to you!
