### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Blackhorse1988** [antoinelame/GazeTracking#11]
Didn´t modified anything on the code and get these error. 
dlib version is 19.9, Package requirement 19.16.0 is needed. Is that important?

Traceback (most recent call last):
  File "C:/Users/XXXXX/PycharmProjects/untitled2/example.py", line 9, in <module>
    gaze = GazeTracking()
  File "C:\Users\XXXXX\PycharmProjects\untitled2\gaze_tracking\gaze_tracking.py", line 28, in __init__
    self._predictor = dlib.shape_predictor(model_path)
RuntimeError: Error deserializing object of type int

Process finished with exit code 1

**Comment by antoinelame** [comment]
Hi @Blackhorse1988 
It's not about dlib version. Your `shape_predictor_68_face_landmarks.dat` is corrupted. It seems that because Git LFS, a lot of people are in the same situation... Check [this issue to solve it](https://github.com/antoinelame/GazeTracking/issues/9).

**Comment by Blackhorse1988** [comment]
great, it works! :)

**Comment by Blackhorse1988** [comment]
Thank you very much!
