### ISSUE TITLE
What kind of webcam are you using?

### ISSUE THREAD

**Issue by TimBluesWin** [antoinelame/GazeTracking#15]
I am currently trying to track the gaze (using horizontal_ratio() method) using your program, however I think the results are still not up to my expectations. (i.e it really often says "Looking Left", only seldom says "Looking Right"). I have changed the number of frames for calibration, as well as tweaking the pupil size, but still the results are roughly the same. I wonder if this is related to the webcam, as well as the lighting conditions. I am currently using webcam shipped from my ASUS X456U, and using Trisquel 8.0 Linux Distro.

Output when using v4l2-ctl --list-devices:

```
USB2.0 VGA UVC WebCam (usb-0000:00:14.0-6):
	/dev/video0
```
Thank you.

**Comment by antoinelame** [comment]
Hi @TimBluesWin 
I use a MacBook's webcam but I already tried on another webcams with good results. It's a sure thing that a good quality and good lighting conditions help a lot. Could you tell me more about what you get? What is inaccurate: the gaze direction (left, center, right) or the detection of your pupils? Or both?
