### ISSUE TITLE
RuntimeError: Error deserializing object of type int

### ISSUE THREAD

**Issue by sdasara95** [antoinelame/GazeTracking#17]
Looks like we need to download this file: http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2

and put it in the trained model folder

**Comment by antoinelame** [comment]
With Git LFS, if you download the project as a "zip" instead of cloning it, you'll miss this file. You can read: https://github.com/antoinelame/GazeTracking/issues/9
