### ISSUE TITLE
Computation of pupil_right_coords

### ISSUE THREAD

**Issue by yanyukang** [antoinelame/GazeTracking#20]
![image](https://user-images.githubusercontent.com/51065640/62187047-ac62c380-b39a-11e9-9bfa-3651c1928e4d.png)

Hi,
I think "self.eye_left.pupil.x" should be "self.eye_right.pupil.x" here.

**Comment by antoinelame** [comment]
Hi @yanyukang,
You're absolutely right! I'm fixing it.

Thank you for spotting the error
