### ISSUE TITLE
Automatic Calibration

### ISSUE THREAD

**Issue by EderSant** [antoinelame/GazeTracking#31]
Hi @Antoinelame

I would like to know how I do it if I want to disable automatic calibration and use threshold values that I have informed. What should I do for this? I am having trouble with automatic calibration. I saw that @Blackhorse1988 made this change and was able to find a threshold value that would meet his need. I'm a little lost on how to do it.

**Comment by antoinelame** [comment]
Hello @EderSant,

The `Calibration` class tries to detect the best threshold for your eye. If you prefer to pass your own value, you can directly override the `threshold` value in the `_analyze()` method of the `Eye` class.

If you do that, you can remove these lines:

```python
if not calibration.is_complete():
            calibration.evaluate(self.frame, side)
```

Example:

```python
def _analyze(self, original_frame, landmarks, side):
    # ...

    self.blinking = self._blinking_ratio(landmarks, points)
    self._isolate(original_frame, landmarks, points)

    self.pupil = Pupil(self.frame, YOUR_THRESHOLD_VALUE)
```
