### ISSUE TITLE
question:how to draw the line of gaze?

### ISSUE THREAD

**Issue by Ashing00** [antoinelame/GazeTracking#33]
Hi,sir
   I can run this example as well.and I porting it to C++ version with Dlib/opencv.
everything work well.
but I want to draw a line to indicate the Gaze.
could you teach me How to draw the line of gaze?

**Comment by 1996scarlet** [comment]
Try `draw_3d_arrow` function in [this file](https://github.com/1996scarlet/Laser-Eye/blob/master/video_gaze_test.py)

And [this paper](https://ieeexplore.ieee.org/document/8818661/) can help you to understand the algorithm

```Python3
theta_left, pha_left, end_left = draw_3d_arrow(frame, poi_left)
theta_right, pha_right, end_right = draw_3d_arrow(frame, poi_right)
```

**Comment by Ashing00** [comment]
@1996scarlet 
 thank you ,I will try it.

**Comment by chenti2x** [comment]
@Ashing00 
hello，poi_left = (landmarks[36], landmarks[39], cp[2]), what dose cp[2] mean?

**Comment by antoinelame** [comment]
The library doesn't allow to directly draw a line that indicates the direction of the gaze, but only returns coordinates (x, y) that allow to know the precise precision of the pupil within the eye. If the pupil is on the right side of the eye, then the person is looking to the right.

Maybe you can use it to draw a line, it's up to you! Let me know the results you get.
