### ISSUE TITLE
Calibrate

### ISSUE THREAD

**Issue by codeYazar** [antoinelame/GazeTracking#4]
Hi antoinelame;
I'm running the program without error, but the laptob screen and webcam (Logitech C920) need to be calibrated? The given coordinates are working according to the Laptob screen or the webcam screen .. Thanks.

**Comment by antoinelame** [comment]
Hi,
Yes, a calibration may be necessary according to your eye's color and your webcam. If you need it, change the threshold value (currently at 20) in `pupil.py` line 29. Like so for example:

new_frame = cv2.threshold(new_frame, 50, 255, cv2.THRESH_BINARY)[1]

Don't hesitate to increase the value, especially if your eyes are light.
I'm working on an auto-calibration for next versions.

**Comment by codeYazar** [comment]
Thanks for your answer.
I'm looking forward to the automatic calibration.

But what environment is the current coordinates? Webcam or labtop screen

**Comment by antoinelame** [comment]
Coordinates of the webcam's frame

**Comment by codeYazar** [comment]
thanks antoinelame..

**Comment by Sayantan17** [comment]
> Coordinates of the webcam's frame

Hello, Antonio, is there way to change it, so it works on the co-ordinates of the image/video rather than the webcam?
