### ISSUE TITLE
error in dlib 

### ISSUE THREAD

**Issue by smane2000** [antoinelame/GazeTracking#41]
Hi antoinelame your project is really super coll and i loved it... After getting inspired by you even i'm trying to do it but i'm getting this error "module dlib has no 'get_frontal_face_detector' member"...please help me to remove this error i'm not able to solve this error...i hope u reply to me as soon as possible.!!!!!

**Comment by antoinelame** [comment]
Hello @smane2000,

You may have a wrong version of dlib. Make sure it's the `19.16.0` as mentioned in the `requirements.txt`. You can do:
```
pip install -r requirements.txt
```

Let me know if it solves your issue!

**Comment by smane2000** [comment]
Hi antoinelame Thanx for replying me...as u told me to install the dlib version 19.16.0 , I did it by uninstalling the version 19.19.0 ..then to I'm getting the same error.. And in terminal and command prompt it says requirement already satisfied.. So what should i do??

**Comment by antoinelame** [comment]
Can you open your Python interpreter and type the following:

```
import dlib

print(dlib)
print(dlib.__file__)
print(dlib.__version__)
```

And then, copy paste the result here

**Comment by smane2000** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dlib' has no attribute '__version__'
