### ISSUE TITLE
Unable to install dlib pkg with python 3.11.8 and pip 24.2

### ISSUE THREAD

**Issue by ebarriosarusd** [antoinelame/GazeTracking#91]
I installed the 4 dependencies from the article that was provided but still getting this error message.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dlib)

**Comment by SuryamShaurya** [comment]
> I installed the 4 dependencies from the article that was provided but still getting this error message.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for dlib Failed to build dlib ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dlib)

Any Solution?
